"""add claimed_at to jobs

Revision ID: 75a845575d2e
Revises: 79cb2ee38481
Create Date: 2026-08-23 15:09:36.624025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75a845575d2e'
down_revision: Union[str, Sequence[str], None] = '79cb2ee38481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'claimed_at')
    # ### end Alembic commands ###
