"""add next_attempt_at to jobs

Revision ID: 9e4822cbf157
Revises: 75a845575d2e
Create Date: 2026-08-27 14:57:09.431312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4822cbf157'
down_revision: Union[str, Sequence[str], None] = '75a845575d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'next_attempt_at')
    # ### end Alembic commands ###
