"""add effect_key and unique constraint to side_effects

Revision ID: dbe13b69056d
Revises: 4b0e6dcfdfa1
Create Date: 2026-09-01 15:01:48.897023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe13b69056d'
down_revision: Union[str, Sequence[str], None] = '4b0e6dcfdfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('side_effects', sa.Column('effect_key', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_side_effects_effect_key', 'side_effects', ['effect_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_side_effects_effect_key', 'side_effects', type_='unique')
    op.drop_column('side_effects', 'effect_key')
    # ### end Alembic commands ###
